### ISSUE TITLE
Link on the obrary.com site doesn't work

### ISSUE THREAD

**Issue by ben-hawks** [Obrary/Living-Hinge-Swatches#1]
Hello!

Less of an issue with the files themselves, but on orbary.com, the link/button to download these files doesn't actually download them, instead looping back to the same page. 

https://obrary.com/collections/open-designs/products/living-hinge-patterns

Figured I'd give a heads up, thanks for these!

**Comment by eric-schleicher** [comment]
Thanks for the heads up, we'll look into it.
